// <auto-generated />
namespace GiraffeWithIdentity.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<MyDbContext.ApplicationDbContext>)>]
[<Migration("20220213001824_Initial")>]
type Initial() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "AspNetRoles"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                Name =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                        ,maxLength = Nullable(256)
                    )
                NormalizedName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                        ,maxLength = Nullable(256)
                    )
                ConcurrencyStamp =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_AspNetRoles", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUsers"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                UserName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                        ,maxLength = Nullable(256)
                    )
                NormalizedUserName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                        ,maxLength = Nullable(256)
                    )
                Email =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                        ,maxLength = Nullable(256)
                    )
                NormalizedEmail =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                        ,maxLength = Nullable(256)
                    )
                EmailConfirmed =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
                PasswordHash =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                SecurityStamp =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                ConcurrencyStamp =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                PhoneNumber =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                PhoneNumberConfirmed =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
                TwoFactorEnabled =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
                LockoutEnd =
                    table.Column<DateTimeOffset>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                LockoutEnabled =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
                AccessFailedCount =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_AspNetUsers", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetRoleClaims"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    ).Annotation("Sqlite:Autoincrement", true)
                RoleId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                ClaimType =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                ClaimValue =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_AspNetRoleClaims", (fun x -> (x.Id) :> obj)) |> ignore
                    table.ForeignKey(
                        name = "FK_AspNetRoleClaims_AspNetRoles_RoleId",
                        column = (fun x -> (x.RoleId) :> obj)
                        ,principalTable = "AspNetRoles"
                        ,principalColumn = "Id"
                        ,onDelete = ReferentialAction.Cascade
                        ) |> ignore

                ) 
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUserClaims"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    ).Annotation("Sqlite:Autoincrement", true)
                UserId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                ClaimType =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                ClaimValue =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_AspNetUserClaims", (fun x -> (x.Id) :> obj)) |> ignore
                    table.ForeignKey(
                        name = "FK_AspNetUserClaims_AspNetUsers_UserId",
                        column = (fun x -> (x.UserId) :> obj)
                        ,principalTable = "AspNetUsers"
                        ,principalColumn = "Id"
                        ,onDelete = ReferentialAction.Cascade
                        ) |> ignore

                ) 
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUserLogins"
            ,columns = (fun table -> 
            {|
                LoginProvider =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                ProviderKey =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                ProviderDisplayName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                UserId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_AspNetUserLogins", (fun x -> (x.LoginProvider, x.ProviderKey) :> obj)) |> ignore
                    table.ForeignKey(
                        name = "FK_AspNetUserLogins_AspNetUsers_UserId",
                        column = (fun x -> (x.UserId) :> obj)
                        ,principalTable = "AspNetUsers"
                        ,principalColumn = "Id"
                        ,onDelete = ReferentialAction.Cascade
                        ) |> ignore

                ) 
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUserRoles"
            ,columns = (fun table -> 
            {|
                UserId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                RoleId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_AspNetUserRoles", (fun x -> (x.UserId, x.RoleId) :> obj)) |> ignore
                    table.ForeignKey(
                        name = "FK_AspNetUserRoles_AspNetRoles_RoleId",
                        column = (fun x -> (x.RoleId) :> obj)
                        ,principalTable = "AspNetRoles"
                        ,principalColumn = "Id"
                        ,onDelete = ReferentialAction.Cascade
                        ) |> ignore

                    table.ForeignKey(
                        name = "FK_AspNetUserRoles_AspNetUsers_UserId",
                        column = (fun x -> (x.UserId) :> obj)
                        ,principalTable = "AspNetUsers"
                        ,principalColumn = "Id"
                        ,onDelete = ReferentialAction.Cascade
                        ) |> ignore

                ) 
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUserTokens"
            ,columns = (fun table -> 
            {|
                UserId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                LoginProvider =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                Name =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                Value =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_AspNetUserTokens", (fun x -> (x.UserId, x.LoginProvider, x.Name) :> obj)) |> ignore
                    table.ForeignKey(
                        name = "FK_AspNetUserTokens_AspNetUsers_UserId",
                        column = (fun x -> (x.UserId) :> obj)
                        ,principalTable = "AspNetUsers"
                        ,principalColumn = "Id"
                        ,onDelete = ReferentialAction.Cascade
                        ) |> ignore

                ) 
        ) |> ignore

        migrationBuilder.InsertData(
            table = "AspNetRoles",
            columns = [| "Id"; "ConcurrencyStamp"; "Name"; "NormalizedName" |],
            values = [| "d22236a0-a3bd-4255-afca-c54ba9127a62" :> obj; "f16a0f75-303d-49a4-9f4b-b011432aa17a" :> obj; "admin" :> obj; "ADMIN" :> obj |]
        ) |> ignore

        migrationBuilder.InsertData(
            table = "AspNetRoles",
            columns = [| "Id"; "ConcurrencyStamp"; "Name"; "NormalizedName" |],
            values = [| "9f1825b4-fa25-42f2-9280-56fb0b176420" :> obj; "ee931bc9-b663-491b-8cfe-dc56f551cbe2" :> obj; "user" :> obj; "USER" :> obj |]
        ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_AspNetRoleClaims_RoleId"
            ,table = "AspNetRoleClaims"
            ,column = "RoleId"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "RoleNameIndex"
            ,table = "AspNetRoles"
            ,column = "NormalizedName"
            ,unique = true
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_AspNetUserClaims_UserId"
            ,table = "AspNetUserClaims"
            ,column = "UserId"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_AspNetUserLogins_UserId"
            ,table = "AspNetUserLogins"
            ,column = "UserId"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_AspNetUserRoles_RoleId"
            ,table = "AspNetUserRoles"
            ,column = "RoleId"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "EmailIndex"
            ,table = "AspNetUsers"
            ,column = "NormalizedEmail"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "UserNameIndex"
            ,table = "AspNetUsers"
            ,column = "NormalizedUserName"
            ,unique = true
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "AspNetRoleClaims"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUserClaims"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUserLogins"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUserRoles"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUserTokens"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetRoles"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUsers"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "5.0.14")
            |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", (fun b ->

            b.Property<string>("Id")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("ConcurrencyStamp")

                .IsConcurrencyToken().IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Name")
                .IsRequired(false)
                .HasMaxLength(256)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("NormalizedName")
                .IsRequired(false)
                .HasMaxLength(256)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("NormalizedName")
                .IsUnique()
                .HasDatabaseName("RoleNameIndex") |> ignore

            b.ToTable("AspNetRoles") |> ignore

            b.HasData([| 
                {| Id = "d22236a0-a3bd-4255-afca-c54ba9127a62"; ConcurrencyStamp = "f16a0f75-303d-49a4-9f4b-b011432aa17a"; Name = "admin"; NormalizedName = "ADMIN"; |}
                {| Id = "9f1825b4-fa25-42f2-9280-56fb0b176420"; ConcurrencyStamp = "ee931bc9-b663-491b-8cfe-dc56f551cbe2"; Name = "user"; NormalizedName = "USER"; |}
             |]) |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("ClaimType")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("ClaimValue")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("RoleId")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("RoleId") |> ignore

            b.ToTable("AspNetRoleClaims") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", (fun b ->

            b.Property<string>("Id")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<int>("AccessFailedCount")
                .IsRequired(true)
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("ConcurrencyStamp")

                .IsConcurrencyToken().IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Email")
                .IsRequired(false)
                .HasMaxLength(256)
                .HasColumnType("TEXT") |> ignore
            b.Property<bool>("EmailConfirmed")
                .IsRequired(true)
                .HasColumnType("INTEGER") |> ignore
            b.Property<bool>("LockoutEnabled")
                .IsRequired(true)
                .HasColumnType("INTEGER") |> ignore
            b.Property<Nullable<DateTimeOffset>>("LockoutEnd")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("NormalizedEmail")
                .IsRequired(false)
                .HasMaxLength(256)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("NormalizedUserName")
                .IsRequired(false)
                .HasMaxLength(256)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("PasswordHash")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("PhoneNumber")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<bool>("PhoneNumberConfirmed")
                .IsRequired(true)
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("SecurityStamp")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<bool>("TwoFactorEnabled")
                .IsRequired(true)
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("UserName")
                .IsRequired(false)
                .HasMaxLength(256)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("NormalizedEmail")
                .HasDatabaseName("EmailIndex") |> ignore


            b.HasIndex("NormalizedUserName")
                .IsUnique()
                .HasDatabaseName("UserNameIndex") |> ignore

            b.ToTable("AspNetUsers") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("ClaimType")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("ClaimValue")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("UserId")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("UserId") |> ignore

            b.ToTable("AspNetUserClaims") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", (fun b ->

            b.Property<string>("LoginProvider")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("ProviderKey")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("ProviderDisplayName")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("UserId")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("LoginProvider", "ProviderKey") |> ignore


            b.HasIndex("UserId") |> ignore

            b.ToTable("AspNetUserLogins") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", (fun b ->

            b.Property<string>("UserId")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("RoleId")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("UserId", "RoleId") |> ignore


            b.HasIndex("RoleId") |> ignore

            b.ToTable("AspNetUserRoles") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", (fun b ->

            b.Property<string>("UserId")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("LoginProvider")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Name")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Value")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("UserId", "LoginProvider", "Name") |> ignore

            b.ToTable("AspNetUserTokens") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole",null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser",null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser",null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole",null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser",null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser",null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

